### ISSUE TITLE
No longer works in Linux!!

### ISSUE THREAD

**Issue by oliverhbailey** [Neon22/inkscape-jigsaw#12]
This control no longer appears in inkscape version 0.92 when put in ~./config/inkscape/extwensions

**Comment by Neon22** [comment]
Please check the install instructions on here:
https://inkscape.org/~Neon22/%E2%98%85lasercut-jigsaw

It seems to be working for most people on windows and linux in 0.92

**Comment by oliverhbailey** [comment]
The wrong folder is specified for the extension in Ubuntu 19.04. The proper
path is defined at the Scorchworks K40 Whisper site. The step by step
instructions there are correct.

I followed the steps there and it works perfectly on Ubuntu 19.04 and
Debian 10.

Thank you,
Great extension.

Oliver Bsiley

**Comment by Neon22** [comment]
You're most welcome.
