### ISSUE TITLE
Just for note

### ISSUE THREAD

**Issue by vmario89** [Neon22/inkscape-jigsaw#17]
by the way found some more jigsaw stuff on the web. but your's is the most advanced i think

https://github.com/RainyDayHiker/Inkscape_Jigsaw_Puzzle
https://github.com/minirevollo/Inkscape-Puzzle-Generator

**Comment by Neon22** [comment]
Thanks. Yes I think it works pretty well.
I was going to (one day) add the feature where you can call inkscape to do booleans . I think suv has an extension. That way I could remove all that boolean code. Haven't go to it yet - of course :(

**Comment by Neon22** [comment]
Thanks heaps for your work on this. I had to rummage around in the inx file for a while but got it all working finally.
Cheers...
