### ISSUE TITLE
Invalid Syntax Error with Inkscape 1.0

### ISSUE THREAD

**Issue by mikestan** [Neon22/inkscape-jigsaw#18]
Looks like Inkscape got updated on my PC - now ver 1.0 (4035a4fb49, 2020-05-01) - and now Lasercut Jigsaw no longer works. Thoughts? Here is the output:

  File "Lasercut-jigsaw.py", line 43
    def randomize((x, y), radius, norm=True, absolute=False):
                  ^
SyntaxError: invalid syntax

**Comment by Neon22** [comment]
all pull requests merged. Are you using the code here or on the inkscape download - which is not yet updated ?

**Comment by Neon22** [comment]
Issues fixed for inkscape 1.0.
New zip file uploaded to extensions on inkscape.
This repo uptodate.
Closing this issue.

**Comment by mikestan** [comment]
> all pull requests merged. Are you using the code here or on the inkscape download - which is not yet updated ?

FWIW, I tried both yet thought this might be the master...

Looks great - just installed it. Many thanks 🧩😷👍!!!!
