### ISSUE TITLE
Older Jigsaw Version

### ISSUE THREAD

**Issue by jonashuber1** [Neon22/inkscape-jigsaw#20]
Dear Neon22,

Ive been working on a Project recently where I need 2 Extensions of Inkscape, however those 2 sadly do not Work with the same Version of the Program.
Unfortunately I cant find a older Version of your Extension online. Would it be possible for you to send me the older Version of Inkscape?

Kind Regards
Jonas Huber

**Comment by Neon22** [comment]
I had a look around but I have not kept one. so sorry. what is the other project that needs to be updated. Maybe I can fix that for you ?

**Comment by jonashuber1** [comment]
> I had a look around but I have not kept one. so sorry. what is the other project that needs to be updated. Maybe I can fix that for you ?

Thank you for looking and the quick answer.
The second Extension isnt one of yours. Its CutWizard, which so far doesnt work on V1.0 of InkScape.
My solution so far is that I have the older Version of InkScape installed as .exe and V1.0 from the Windows App Store. Having the same Application on my PC twice is annoying so I now hope theres an CutWizard Update soon. Thank you again.

**Comment by Neon22** [comment]
Do you have url of the inkscape extension for cutwizard? I cannot find it.
I did find inkcut - have you tried that ?

**Comment by jonashuber1** [comment]
> Do you have url of the inkscape extension for cutwizard? I cannot find it.
> I did find inkcut - have you tried that ?

https://www.hobbyplotter.de/download/content/index.php?id=43

I have not tried inkcut so far.

**Comment by jonashuber1** [comment]
I just found an older Version of Jigsaw on one of the contributors Sites
https://github.com/jonadem/inkscape-jigsaw
Seems to work perfectly fine.
Thank you so much for your effort.

**Comment by Neon22** [comment]
I see 4 different downloads and a manual. which one has the inkscape extension ?
Or I'll get them all and try to find it ?

**Comment by Neon22** [comment]
They all have setup programs and I don;t have license keys.
At least you found an old version.
However if you find the inx file and the (probably) python file then email to me neon.mark@gmail.com

**Comment by jonashuber1** [comment]
> They all have setup programs and I don;t have license keys.
> At least you found an old version.
> However if you find the inx file and the (probably) python file then email to me [neon.mark@gmail.com](mailto:neon.mark@gmail.com)

Heres a link directly to the developers Website https://www.plotterhaus.de/downloads/software/cutwizard/
The license key is just the serial number of a plotter as far as I know.
However the link I attached has only an .exe and a .cmd as well.
Again thank you so much for your effort, Im fine working with the older version since I dont have to switch between programs now and I´ll just switch to the latest InkScape Version as soon as theres a new CutWizard Version compatible with it.
Thanks again!

**Comment by Neon22** [comment]
ok. best wishes, cheers. closing
