### ISSUE TITLE
Older version needed

### ISSUE THREAD

**Issue by uwefrank** [Neon22/inkscape-jigsaw#21]
The actual version does not run under Inkscape 0.92. I must however keep that beacuse of another extension I need. Would it be possible to provide also an previous version of the extension. Besides that it is really good.

**Comment by Neon22** [comment]
what is the other extension that needs updating. Maybe I can fix that one.

**Comment by uwefrank** [comment]
Hi Neon22,
pretty quick reply! Thanks.
the other extension is the JTech Photonics gcode generator. It works only well under 0.92. When I use the new version of it (beta)  under 1.01 it generates gcode that tries to drive my 3D printer/cutter head over the limits of the frame. There is some scaling issue. I already thought about writing a postprocessor. As far as I coudl find out it upscales the coordinates by a factor of 3.5 or so. Maybe a inch/centimeter issue? I looked already through the code but it is really a big chunk of code.

So I thought it would be the easiest to run a previous version of the jigsaw extension until the JTech guys have fixed the code. It is already reported as a bug.
 
Neon22 schrieb:

**Comment by uwefrank** [comment]
Besides that I want to say that this is a great extension. Like it a lot.

**Comment by Neon22** [comment]
This page indicates there is a beta for V1.0
- https://jtechphotonics.com/?page_id=1980
- Have you tried that ?
The scaling will be the issue but almost impossible to fix as a postprocess on the Gcode.

Please let me know how you get on ?

**Comment by Neon22** [comment]
Oops yes I see that. sorry not concentrating :(
I'll check it

**Comment by uwefrank** [comment]
Yes, I tried that too.  No change. There's a fundamental bug in.

Neon22 schrieb:

**Comment by Neon22** [comment]
Looked through the code. I added a note on the Jumbo github issue. It looks to me like the some units are being assumed.
I don't have time to try to fix the code just at this time and the only way I could test it would be to have a result that was correct to compare to.

So I'd suggest you try creating a simple shape with a new doc initialised in mm or inches, or pixels and submit the svg file that fails as well as any that work as examples to the jumbo issue:
- https://github.com/JTechPhotonics/J-Tech-Photonics-Laser-Tool/issues/27.

**Comment by uwefrank** [comment]
Ok. Thanks for caring. addtl comment: If a shape is created in Inkscape it works fine in both versions. But if it is pasted from an external source it does not work. Creates sometimes even negative y coordinates in 1.01.

**Comment by Neon22** [comment]
OK that's super useful news,
alas link does not resolve. svg is text and probably not too large you could cut and paste it in here.

**Comment by Neon22** [comment]
OK. They think the bug is fixed. please let me know if its working in latest Inkscape.

**Comment by Neon22** [comment]
@uwefrank did they update and did it work for you. Can we close this issue ?

**Comment by uwefrank** [comment]
Hi Neon22,
yes, please close down the issue.
Thanks.

Neon22 schrieb:
