### ISSUE TITLE
Not compatible with 1.3

### ISSUE THREAD

**Issue by StrangerGithuber** [Neon22/inkscape-jigsaw#24]
Hi,
I can't install this because it supports maximum inkscape 1.2.
Now the newest version is 1.3.
I hope someone can update this. Thanks in advance.

**Comment by Neon22** [comment]
tested it in 1.3. works fine...
Can you test please ?
Did you do manual install in %appdata%\inkscape\extensions, or use some other method ?
windows or linux ?
