### ISSUE TITLE
Inkscape units API changes

### ISSUE THREAD

**Issue by IMDagger** [Neon22/inkscape-jigsaw#3]
Hello. I guess it's necessary to replace **inkex.unittouu** by **self.unittouu** due to the http://wiki.inkscape.org/wiki/index.php/Notes_On_Units_Handling_in_Extensions_in_0.91

**Comment by IMDagger** [comment]
I changed for me, and it solved the traceback, so I could make a pull request. Thanks.

**Comment by bsimpson53** [comment]
I've just hit this as well

**Comment by Neon22** [comment]
This change already made in 798 of pyhthon file.
Are you using an old version ?

**Comment by bsimpson53** [comment]
Yeah, old version of inkscape :)
