### ISSUE TITLE
Inkscape 0,91 - No extension under "render" folder

### ISSUE THREAD

**Issue by hhalene** [Neon22/inkscape-jigsaw#6]
I have installed Inkscape 0,91 on windows 10 server
I put your files sunder extension folder

But after restarting application, i don't find your extension in menu : Extensions -> Render

**Comment by Neon22** [comment]
I don't know anything about windows server but try this:
- In file browser - in address line type: %appdata%
- This should navigate to a folder with a name something like this:
    C:\Users\<username>\AppData\Roaming

In here you should see many directories including one for Inkscape.
- Open the Inkscape/extensions folder
- Put the two files - inx and py - in here.
- Restart Inkscape and this should appear on an extensions menu.

The menu should be called: Render
The title for this extension will be: Lasercut Jigsaw
