### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by ARKopp** [Neon22/inkscape-jigsaw#7]
I am trying it in inkscape mac but I does not work yet. Is it windows only?

**Comment by Scott216** [comment]
It worked on my Mac.  It can be hard to tell that it did anything because the lines are so thin.

**Comment by ARKopp** [comment]
ah you are correct. I changed it to view outline only.

**Comment by ARKopp** [comment]
great plugin!. Playing around with it now.

**Comment by Neon22** [comment]
The change sin 0.92 have made the lines thinner (def pixels unit changed). I will attempt an update soon.
Its also taken a long time for the Mac version of inkscape to come out - did not even know there was one yet...
