### ISSUE TITLE
Edges with no knobs - enhancement

### ISSUE THREAD

**Issue by LynNor1** [Neon22/inkscape-jigsaw#9]
I would like to add the ability to convert some fraction of puzzle edges to a wavy edge with no knob.  User could turn this option on/off (it would be off by default).  User would specify the percentage of edges that would randomly contain no knobs.
<img width="430" alt="no_knobs_example" src="https://user-images.githubusercontent.com/47004845/59624069-111bd480-90f3-11e9-8cf2-e934253e906e.png">

**Comment by Neon22** [comment]
Its an interesting idea but it can be done manually in  only a few seconds. Have you considered that ?
Just select the knobs you don't want with the node tool and delete the nodes.

**Comment by LynNor1** [comment]
Hi yes I have played with the nodes, but also modified a copy of your code to automatically generate edges with no knobs as shown in the image.  Sorry I am a bit new to GitHub and I think I used the wrong venue to ask you if you would be interested in the changes I made.  If you are interested, I will submit a pull request, otherwise I'll just keep my own modifications :)  Thanks!

**Comment by Neon22** [comment]
feel free to submit a pull request. Consider doing the changes in a new branch.

**Comment by LynNor1** [comment]
Thank you I did submit a pull request and the changes are on the "dev" branch.
